# Generated by Django 5.1.7 on 2025-03-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
