# Generated by Django 5.1.7 on 2025-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='replacement_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Processing', 'Processing'), ('shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('Refunded', 'Refunded'), ('Replaced', 'Replaced')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Return Requested', 'Return Requested'), ('Return Processing', 'Return Processing'), ('Returned', 'Returned'), ('Replacement Requested', 'Replacement Requested'), ('Replacement Processing', 'Replacement Processing'), ('Replaced', 'Replaced'), ('Cancelled', 'Cancelled')], default='Processing', max_length=50),
        ),
    ]
