# Generated by Django 5.1.7 on 2025-03-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='categories/default.png', upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(default='product_variants/default.png', upload_to='product_variants/'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default='subcategories/default.png', upload_to='subcategories/'),
        ),
    ]
