# Generated by Django 5.1.7 on 2025-03-21 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_category_image_productvariant_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_top_featured',
            field=models.BooleanField(default=False),
        ),
    ]
