# Generated by Django 5.1.7 on 2025-03-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_product_is_top_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage (e.g. 10 for 10%)'),
        ),
    ]
