# Generated by Django 5.1.7 on 2025-03-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='replacement_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='return_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='product',
            name='return_eligible',
            field=models.BooleanField(default=True),
        ),
    ]
